/*Display the total sales value generated by each vendor using ORDER_ITEM.*/
SELECT
    v.vendor_id,
    v.vendor_name,
    SUM(oi.quantity * oi.price_at_purchase) AS total_sales
FROM vendor v
JOIN product p
    ON v.vendor_id = p.vendor_id
JOIN order_item oi
    ON p.product_id = oi.product_id
GROUP BY v.vendor_id, v.vendor_name;